
  Documentation:
    Enabled: false
  LineLength:
    Max: 99
  Metrics/MethodLength:
    Max: 99
  AllCops:
    TargetRubyVersion: 2.5
    Exclude:
      - 'spec/**/*.rb'
      - 'app/admin/*.rb'
      - 'app/controllers/users/omniauth_controller.rb'    