
default: &default
  #adapter: postgresql
  #encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #host: localhost
  #username: wbooks-api
  #password: wbooks-api

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: wbooks
  host: localhost
  username: wbooks-api
  password: wbooks-api

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: wbooks
  host: localhost
  username: wbooks-api
  password: wbooks-api

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: wbooks
  host: localhost
  username: wbooks-api
  password: wbooks-api
