default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: <%= ENV["DEFAULT_ADAPTER"] %>
  encoding: <%= ENV["DEFAULT_ENCODING"] %>
  database: <%= ENV["DEFAULT_DATABASE"] %>
  host: <%= ENV["DEFAULT_HOST"] %>
  username: <%= ENV["DEFAULT_USERNAME"] %>
  password: <%= ENV["DEFAULT_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *development

production:
  database: <%= ENV["DATABASE_DB"] %>
  username: <%= ENV["DATABASE_USR"] %>
  password: <%= ENV["DATABASE_PSW"] %>
  url: <%= ENV["DATABASE_URL"] %>
