default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  database: wbooks
  host: localhost
  username: wbooks-api
  password: wbooks-api

common: &common
  database: <%= ENV["DATABASE_DB"] %>
  username: <%= ENV["DATABASE_USR"] %>
  password: <%= ENV["DATABASE_PSW"] %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *common
