
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: wbooks-api
  password: wbooks-api

development:
  <<: *default
  database: wbooks
  username: wbooks-api
  password: wbooks-api

test:
  <<: *default

production:
  <<: *default
  database: nombre-de-tu-app_production
  username: nombre-de-tu-app
  password: <%= ENV['TRAINING-APP_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
