# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

common: &common
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>
  address: <%= ENV["ADDRESS"] %>
  port: <%= ENV["PORT"] %>
  domain: <%= ENV["DOMAIN"] %>
  authentication: <%= ENV["AUTHENTICATION"] %>
  from_email: <%= ENV["FROM@MAIL"] %>

development:
  secret_key_base: 1b7333657709a8e14d929c518b4befc85655aa71c0f9bd09250123f1d5b2273c0b21c4399e9a68c8b72c356b48475ac856efce63deb08781505a691f76a95aec
  <<: *common

test:
  secret_key_base: 07822b15f8f8e1b6fee95d6fc60e31167b017e67f26f6929bcbdc396a073a635b0c113d399e55970e1ef0c1aa973369c4f46a5cdf640ab0627107e59244ed866
  <<: *common

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *common
